# Site Settings
baseurl: ""
url: "https://juanjfeng.github.io/AKWWW/"
exclude: ['README.md']

# Sass/SCSS
sass:
  sass_dir: css
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Remove html extension
permalink: /:title/

keep_files: [assets/js/swiper.min.js.map]